msg = 'Olá Mundo'
print(msg)
print('1-Criar Script que leia o nome da pessoa e mostre uma mensagem') 
print('de Boas-Vindas de acordo com a mensagem digitada')
input('Qual é o seu nome ?')
nome = input('Qual e o seu nome ? ')
print('Olá',nome,',seja bem-vindo !')
print('Olá {}, seja bem-vindo !'. format(nome))
idade = input('Quantos anos você tem ?')
print(idade)
print('2-Criar Script que leia o dia, o mês e o ano de nascimento e') 
print('mostr uma mensagem com a data formatada')
nasci = input('Qual dia, mês e ano você nasceu ?')
print(nasci)
peso = input('Quantos kg você tem ?')
print(peso)
num1 = input(20)
print(num1)
num2 = input(80)
print(num2)
print(20+80)

