msg = 'Olá Mundo'
print(msg)

nome = input('Qual é o seu nome : ')
print('Prazer em te conhecer {}!' .format(nome))

print('20Prazer em te conhecer {:20}!' .format(nome))
print('19Prazer em te conhecer {:19}!' .format(nome))
print('18Prazer em te conhecer {:18}!' .format(nome))
print('17Prazer em te conhecer {:17}!' .format(nome))
print('16Prazer em te conhecer {:16}!' .format(nome))
print('15Prazer em te conhecer {:15}!' .format(nome))
print('14Prazer em te conhecer {:14}!' .format(nome))
print('13Prazer em te conhecer {:13}!' .format(nome))
print('12Prazer em te conhecer {:12}!' .format(nome))
print('11Prazer em te conhecer {:11}!' .format(nome))
print('10Prazer em te conhecer {:10}!' .format(nome))
print('09Prazer em te conhecer {:09}!' .format(nome))
print('08Prazer em te conhecer {:08}!' .format(nome))
print('07Prazer em te conhecer {:07}!' .format(nome))
print('06Prazer em te conhecer {:06}!' .format(nome))
print('05Prazer em te conhecer {:05}!' .format(nome))
print('04Prazer em te conhecer {:04}!' .format(nome))
print('03Prazer em te conhecer {:03}!' .format(nome))
print('02Prazer em te conhecer {:02}!' .format(nome))
print('01Prazer em te conhecer {:01}!' .format(nome))

print('10Prazer em te conhecer {:>10}!' .format(nome))
print('09Prazer em te conhecer {:>09}!' .format(nome))
print('08Prazer em te conhecer {:>08}!' .format(nome))
print('07Prazer em te conhecer {:>07}!' .format(nome))
print('06Prazer em te conhecer {:>06}!' .format(nome))
print('05Prazer em te conhecer {:>05}!' .format(nome))
print('04Prazer em te conhecer {:>04}!' .format(nome))
print('03Prazer em te conhecer {:>03}!' .format(nome))
print('02Prazer em te conhecer {:>02}!' .format(nome))
print('01Prazer em te conhecer {:>01}!' .format(nome))

print('01Prazer em te conhecer {:<20}!' .format(nome))

print('02Prazer em te conhecer {:^20}!' .format(nome))
print('02Prazer em te conhecer {:^19}!' .format(nome))
print('02Prazer em te conhecer {:^18}!' .format(nome))
print('02Prazer em te conhecer {:^17}!' .format(nome))
print('02Prazer em te conhecer {:^16}!' .format(nome))
print('02Prazer em te conhecer {:^15}!' .format(nome))

print('03Prazer em te conhecer {:=^20}!' .format(nome))
print('03Prazer em te conhecer {:=^19}!' .format(nome))
print('03Prazer em te conhecer {:=^18}!' .format(nome))
print('03Prazer em te conhecer {:=^17}!' .format(nome))
print('03Prazer em te conhecer {:=^16}!' .format(nome))
print('03Prazer em te conhecer {:=^15}!' .format(nome))